Name:           ros-kinetic-xiaoqiang-bringup
Version:        0.0.9
Release:        0%{?dist}
Summary:        ROS xiaoqiang_bringup package

Group:          Development/Libraries
License:        MIT
URL:            http://www.bwbot.org/content/xiaoqiang
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-kinetic-message-runtime
Requires:       ros-kinetic-rospy
Requires:       ros-kinetic-rplidar-ros
Requires:       ros-kinetic-std-msgs
Requires:       ros-kinetic-usb-cam
Requires:       ros-kinetic-web-video-server
Requires:       ros-kinetic-xiaoqiang-description
Requires:       ros-kinetic-xiaoqiang-driver
Requires:       ros-kinetic-xiaoqiang-monitor
BuildRequires:  ros-kinetic-catkin
BuildRequires:  ros-kinetic-message-runtime
BuildRequires:  ros-kinetic-rospy
BuildRequires:  ros-kinetic-rplidar-ros
BuildRequires:  ros-kinetic-std-msgs
BuildRequires:  ros-kinetic-usb-cam
BuildRequires:  ros-kinetic-web-video-server
BuildRequires:  ros-kinetic-xiaoqiang-description
BuildRequires:  ros-kinetic-xiaoqiang-driver
BuildRequires:  ros-kinetic-xiaoqiang-monitor

%description
xiaoqiang bringup package, including launch files for many devices

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Thu Jun 07 2018 Randoms <randoms@bwbot.org> - 0.0.9-0
- Autogenerated by Bloom

* Fri Jun 01 2018 Randoms <randoms@bwbot.org> - 0.0.7-0
- Autogenerated by Bloom

* Thu May 31 2018 Randoms <randoms@bwbot.org> - 0.0.6-0
- Autogenerated by Bloom

* Wed May 30 2018 Randoms <randoms@bwbot.org> - 0.0.5-0
- Autogenerated by Bloom

